# Default values for behave-content-indexer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  # -- Number of desired pods.
  # We use 3 minimum to assure no outage durring rollout/preemtible node restarts
  replicas: 3

image:
  # -- image repository
  repository: eu.gcr.io/logical-sled-220910/strg/behave/content-indexer
  # -- image tag
  tag: ""
  # -- image pull policy
  # pullPolicy: IfNotPresent

securityContext:
  capabilities:
    drop:
      # -- drop all privileges as we dont need them
      - ALL
  # -- set root fs to read only for security reasons
  readOnlyRootFilesystem: true
  # -- do not allow privilege escalation for security reasons
  allowPrivilegeEscalation: false
  # -- do not run as root for security reasons
  runAsNonRoot: true
  # -- run as user with <id>
  runAsUser: 1000

env:
  # -- The timezone in the container
  TZ: Europe/Vienna
  # -- The default python environment
  PYTHON_ENV: "production"
  # -- beHave client id used in logging reference aswel as in NATS message routing
  BEHAVE_CLIENT_ID: strg
  # -- content-indexer api to use
  API: nats
  # -- elasticsearch host ip or fqdn
  ELASTIC_HOST: ""
  # -- elasticsearch port defaults to 9200
  ELASTIC_PORT: "9200"
  # -- use the noen parser or not
  USE_NOEN_PARSER: "false"
  # -- the nats server address
  NATS_SERVER: ""
  # -- the nats user
  NATS_USER: ""
  # -- the nats password
  NATS_PASS: ""
