apiVersion: v2
type: application
appVersion: 5.0.12
description: STRG.BeHave tracking-service
name: behave-tracking-service
version: 0.1.4
kubeVersion: ">=1.16.0-0"
keywords:
  - behave
  - tracking-service
home: https://github.com/strg-at/tree/main/charts/behave-tracking-service
maintainers:
  - name: Nils Müller
    email: nils.mueller@strg.at
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
