# Default values for behave-tracking-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# IMPORTANT NOTE
#
# This chart inherits from k8s-at-home common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  # -- Number of desired pods.
  # We use 3 minimum to assure no outage durring rollout/preemtible node restarts
  replicas: 3

image:
  # -- image repository
  repository: eu.gcr.io/logical-sled-220910/strg/behave/tracking-service
  # -- image tag
  tag: ""
  # -- image pull policy
  # pullPolicy: IfNotPresent

securityContext:
  capabilities:
    drop:
      # -- drop all privileges as we dont need them
      - ALL
  # -- set root fs to read only for security reasons
  readOnlyRootFilesystem: true
  # -- do not allow privilege escalation for security reasons
  allowPrivilegeEscalation: false
  # -- do not run as root for security reasons
  runAsNonRoot: true
  # -- run as user with <id>
  runAsUser: 1000

env:
  # -- The timezone in the container
  TZ: UTC
  # -- The default nodejs environment
  NODE_ENV: production
  # -- beHave client id used in logging reference aswel as in NATS message routing
  BEHAVE_CLIENT_ID: strg
  # -- beHave websocket connection timeout
  CONNECTION_TIMEOUT: "60000"
  # -- beHave keep alive timeout
  KEEPALIVE_TIMEOUT: "30000"
  # -- the maximum length of bytes before droping websocket frames
  PAYLOAD_MAX_LENGTH: "10000"
  # -- store raw events in db (require a working db connection)
  STORE_RAW_EVENTS: "false"
  # -- websocket listening port
  PORT: "3000"
  # -- the nats server address
  NATS_SERVER: ""
  # -- the nats user
  NATS_USER: ""
  # -- the nats password
  NATS_PASS: ""

# -- Probe configuration
# -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
# @default -- See below
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    # -- Enable the liveness probe
    enabled: false

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    # -- Enable the readiness probe
    enabled: false

  # -- Startup probe configuration
  # @default -- See below
  startup:
    # -- Enable the startup probe
    enabled: false

# -- Configure the services for the chart here.
# Additional services can be added by adding a dictionary key similar to the 'main' service.
# @default -- See below
service:
  main:
    # -- Configure the Service port information here.
    # Additional ports can be added by adding a dictionary key similar to the 'http' service.
    # @default -- See below
    ports:
      http:
        # -- The port number
        port: 3000
