# Default values for behave-tracking-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# IMPORTANT NOTE
#
# This chart inherits from k8s-at-home common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  # -- Number of desired pods.
  # We use 3 minimum to assure no outage durring rollout/preemtible node restarts
  replicas: 3

image:
  # -- image repository
  repository: eu.gcr.io/logical-sled-220910/strg/behave/tracking-service
  # -- image tag
  tag: ""
  # -- image pull policy
  # pullPolicy: IfNotPresent

securityContext:
  capabilities:
    drop:
      # -- drop all privileges as we dont need them
      - ALL
  # -- set root fs to read only for security reasons
  readOnlyRootFilesystem: true
  # -- do not allow privilege escalation for security reasons
  allowPrivilegeEscalation: false
  # -- do not run as root for security reasons
  runAsNonRoot: true
  # -- run as user with <id>
  runAsUser: 1000

service:
  main:
    ports:
      http:
        # -- the service port
        port: 3000

env:
  # -- The timezone in the container
  TZ: Europe/Vienna
  # -- The default nodejs environment
  NODE_ENV: "production"
  # -- beHave client id used in logging reference aswel as in NATS message routing
  BEHAVE_CLIENT_ID: strg
  # -- beHave websocket connection timeout
  CONNECTION_TIMEOUT: "60000"
  # -- beHave keep alive timeout
  KEEPALIVE_TIMEOUT: "30000"
  # -- the maximum length of bytes before droping websocket frames
  PAYLOAD_MAX_LENGTH: "10000"
  # -- store raw events in db (require a working db connection)
  STORE_RAW_EVENTS: "false"
  # -- websocket listening port
  PORT: "3000"
  # -- the nats server address
  NATS_SERVER: ""
  # -- the nats user
  NATS_USER: ""
  # -- the nats password
  NATS_PASS: ""
