{{ include "common.all" . }}
{{- if eq .Values.env.GRAPHQL_URL  "" }}
{{- fail "value for .Values.env.GRAPHQL_URL must be set" }}
{{- end }}
{{- if eq .Values.env.KEYCLOAK_HOST  "" }}
{{- fail "value for .Values.env.KEYCLOAK_HOST must be set" }}
{{- end }}
{{- if eq .Values.env.HOME_URI  "" }}
{{- fail "value for .Values.env.HOME_URI must be set" }}
{{- end }}
