apiVersion: v2
type: application
appVersion: 1.1.0
description: STRG.BeHave blacklist-ui
name: behave-blacklist-ui
version: 0.1.4
kubeVersion: ">=1.16.0-0"
keywords:
  - behave
  - blacklist-ui
home: https://github.com/strg-at/tree/main/charts/behave-blacklist-ui
maintainers:
  - name: Nils Müller
    email: nils.mueller@strg.at
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
