apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- with .Values.config }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
