{{ include "common.all" . }}
{{- if eq .Values.config.app.port  "" }}
{{- fail "value for .Values.config.app.port must be set" }}
{{- end }}
{{- if eq .Values.config.app.host  "" }}
{{- fail "value for .Values.config.app.host must be set" }}
{{- end }}
{{- if eq .Values.config.app.baseUrl  "" }}
{{- fail "value for .Values.config.app.baseUrl must be set" }}
{{- end }}
